import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "../components/NavBar/Navbar";
import NextThemeProvider from "../components/NextThemeProvider/NextThemeProvider";

// font
const notoFont = Noto_Serif({
  subsets: ["latin"], // Adding subsets is mandatory in some Next.js versions
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// meta data for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" className=" h-full antialiased">
      <body className={`${notoFont.className} min-h-full flex flex-col`}>
        <NextThemeProvider>
          <Navbar></Navbar>
          <main className="px-2"> {children}</main>
        </NextThemeProvider>
      </body>
    </html>
  );
}
