import type { Metadata } from "next";
import { Noto_Serif, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/NavBar/Navbar";
import NextThemeProvider from "../components/NextThemeProvider/NextThemeProvider";
import NextAuthProvider from "../components/AuthPage/NextAuthProvider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

// font
const notoFont = Noto_Serif({
  subsets: ["latin"], // Adding subsets is mandatory in some Next.js versions
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const poppins = Poppins({
  subsets: ["latin"], // Adding subsets is mandatory in some Next.js versions
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
// meta data for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className={cn(" h-full antialiased", "font-sans", inter.variable)}
      >
        <body className={`${notoFont.className} min-h-full flex flex-col`}>
          <NextThemeProvider>
            <div className="w-full max-w-480 mx-auto px-20">
              <Navbar></Navbar>
              <main className="w-full  px-4 md:px-0 mt-30 ">{children}</main>
            </div>
          </NextThemeProvider>
        </body>
      </html>
    </NextAuthProvider>
  );
}
